import os

PATH_TO_REDIRECT_LOOKUP_TABLE = os.environ.get("REDIRECT_LOOKUP_TABLE_PATH")
PATH_TO_PRETRAINED_WORD2VEC_MODEL = os.environ.get("PRETRAINED_EMBEDDINGS_WORD2VEC")
PATH_TO_PRETRAINED_FASTTEXT_MODEL = os.environ.get("PRETRAINED_EMBEDDINGS_FASTTEXT")
