import os

PATH_TO_REDIRECT_LOOKUP_TABLE = os.environ.get("REDIRECT_LOOKUP_TABLE_PATH")

PATH_TO_PRETRAINED_MODEL = os.environ.get("PRETRAINED_EMBEDDINGS")

PATH_TO_STANFORD_CORENLP = os.environ.get("CORENLP_HOME")
