# Consts which are used for statistics column names
SRC_NODE = 'Source_Node'
DST_NODE = 'Dest_Node'
BFS_DIST = 'BFS_Distance'
BFS_TIME = 'BFS_Time'
BFS_DEVELOPED = 'BFS_developed'
BFS_PATH = 'BFS_Path'
NN_DIST = 'NN_Distance'
NN_TIME = 'NN_Time'
NN_DEVELOPED = 'NN_developed'
NN_PATH = 'NN_Path'
ASTAR_DIST = 'A*_Distance'
